tap "caskroom/cask"
tap "caskroom/fonts"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/dupes"
tap "homebrew/services"
tap "homebrew/versions"
tap "gocardless/taps"

brew "reattach-to-user-namespace"
brew "ack"
brew "adns"
brew "autoconf"
brew "ffmpeg"
brew "fontconfig"
brew "freetype"
brew "fzf"
brew "gd"
brew "gettext"
brew "gifsicle"
brew "gmp"
brew "gnupg"
brew "gnutls"
brew "graphviz"
brew "htop"
brew "icu4c"
brew "jpeg"
brew "jq"
brew "lame"
brew "libassuan"
brew "libevent"
brew "libffi"
brew "libgcrypt"
brew "libgpg-error"
brew "libksba"
brew "libpng"
brew "libtasn1"
brew "libtiff"
brew "libtool"
brew "libunistring"
brew "libusb"
brew "micro"
brew "nettle"
brew "node"
brew "npth"
brew "nvm"
brew "openssl"
brew "p11-kit"
brew "pinentry"
brew "pkg-config"
brew "postgresql@9.4"
brew "rbenv"
brew "readline"
brew "ruby-build"
brew "tmux"
brew "watch"
brew "webp"
brew "x264"
brew "xvid"
brew "yarn"
brew "go"
brew "draupnir"
brew "qt@5.5"
brew "awscli"
brew "terraform"

# brew "elixir"
# brew "erlang"
# brew "findutils"
# brew "gdbm"
# brew "geoip"
# brew "ghc"
# brew "git"
# brew "glib"
# brew "gnu-tar"
# brew "gnuplot"
# brew "hub"
# brew "imagemagick"
# brew "isl014"
# brew "isl@0.14"
# brew "jpegoptim"
# brew "jq"
# brew "leiningen"
# brew "leptonica"
# brew "libmpc"
# brew "libsass"
# brew "libxml2"
# brew "libyaml"
# brew "logsearch"
# brew "lua"
# brew "mad"
# brew "maven"
# brew "memcached"
# brew "mpfr"
# brew "oniguruma"
# brew "openssl@1.1"
# brew "optipng"
# brew "pcre"
# brew "postgresql"
# brew "pyenv"
# brew "python"
# brew "python3"
# brew "qt"
# brew "rabbitmq"
# brew "sbt"
# brew "scala"
# brew "sox"
# brew "terraform"
# brew "tesseract"
# brew "the_silver_searcher"
# brew "unixodbc"
# brew "watchman"
# brew "wireshark"
# brew "wrk"
# brew "wxmac"
# brew "xz"
# brew "zlib"

cask "ableton-live"
cask "caffeine"
cask "docker"
cask "firefox"
cask "iterm2"
cask "karabiner-elements"
cask "keybase"
cask "ngrok"
cask "skype"
cask "slack"
cask "spectacle"
cask "sublime-text"
cask "visual-studio-code"
# cask "google-chrome"

mas "Copy'em Paste", id: 876540291
mas "Xcode", id: 497799835
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Todoist", id: 585829637
